### ISSUE TITLE
综艺只能下载一段，不能下载完整视频

### ISSUE THREAD

**Issue by yimshing** [aklws/youku_spi#1]
例如盒子里的猫第一期

**Comment by aklws** [comment]
因为在优酷的分享iframe里面现在是通过替换video标签里面的视频地址，但是我无法判断视频的进度有多长，所以只能下载默认的前三个视频后合并，我会在后面解决这个问题。

**Comment by aklws** [comment]
更换了视频解析接口，现在可以正常下载了。
